# Generated by Django 5.1.3 on 2024-12-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("accountId", models.AutoField(primary_key=True, serialize=False)),
                ("accountName", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "account",
            },
        ),
    ]
