# Generated by Django 5.1.3 on 2024-12-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FruitMart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fruitName", models.CharField(max_length=50)),
                ("counter", models.IntegerField()),
            ],
            options={
                "db_table": "FruitMart",
            },
        ),
    ]
